### ISSUE TITLE
Internal server error when user has an old db in session

### ISSUE THREAD

**Issue by sbidoul** [OCA/rest-framework#113]
When a user accesses Odoo (any URL) while previously logged in on a database that has been removed, the server returns an 500 with the following stack trace:

```
2021-02-14 20:02:47,914 1794 ERROR **** werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/service/wsgi_server.py", line 140, in application
    return ProxyFix(application_unproxied)(environ, start_response)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/http.py", line 1424, in dispatch
    request = self.get_request(httprequest)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/addons/base_rest/http.py", line 219, in get_request
    odoo.registry(db)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/__init__.py", line 104, in registry
    return modules.registry.Registry(database_name)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/modules/registry.py", line 62, in __new__
    return cls.new(db_name)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/modules/registry.py", line 74, in new
    registry.init(db_name)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/modules/registry.py", line 143, in init
    with closing(self.cursor()) as cr:
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/modules/registry.py", line 542, in cursor
    return self._db.cursor()
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/sql_db.py", line 664, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/sql_db.py", line 196, in __init__
    self._cnx = pool.borrow(dsn)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/sql_db.py", line 547, in _locked
    return fun(self, *args, **kwargs)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/odoo/sql_db.py", line 615, in borrow
    **connection_info)
  File "/home/odoo-dev/instance/venv-7.1.85/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "****" does not exist - - -
```

Since base_rest is the only unusual thing in this stack trace... The issue might follow from https://github.com/OCA/rest-framework/pull/83.

**Comment by lmignon** [comment]
This should be fixed by https://github.com/OCA/rest-framework/pull/111
