### ISSUE TITLE
schema2parameters() got an unexpected keyword argument 'location' using base_rest_demo

### ISSUE THREAD

**Issue by erick-tejada** [OCA/rest-framework#137]
Hello,

I am trying to run the base_rest_demo module inside a Modified Odoo Docker Image (which includes all the installs needed by the rest framework modules), and after installing the rest modules on a database (no apparent issues while doing so) I open the Swagger page (http://localhost:8069/api-docs), but get a Fetch Error.

The logs show that `schema2parameters() got an unexpected keyword argument 'location'`:

`Traceback (most recent call last):
  ...
  File "/mnt/extra-addons/oca/rest-framework/base_rest/controllers/api_docs.py", line 38, in api
    return self.make_json_response(service.to_openapi())
  File "/mnt/extra-addons/oca/rest-framework/base_rest/components/service.py", line 183, in to_openapi
    return BaseRestServiceAPISpec(self).to_dict()
  File "/mnt/extra-addons/oca/rest-framework/base_rest/apispec/base_rest_service_apispec.py", line 36, in __init__
    self._generate_paths()
  File "/mnt/extra-addons/oca/rest-framework/base_rest/apispec/base_rest_service_apispec.py", line 74, in _generate_paths
    self._add_method_path(method)
  File "/mnt/extra-addons/oca/rest-framework/base_rest/apispec/base_rest_service_apispec.py", line 66, in _add_method_path
    routing=routing,
  File "/usr/local/lib/python3.5/dist-packages/apispec/core.py", line 280, in path
    plugin.operation_helper(path=path, operations=operations, **kwargs)
  File "/mnt/extra-addons/oca/rest-framework/base_rest/apispec/rest_method_param_plugin.py", line 43, in operation_helper
    input_param.to_openapi_query_parameters(self._service)
  File "/mnt/extra-addons/oca/rest-framework/base_rest_datamodel/restapi.py", line 48, in to_openapi_query_parameters
    return converter.schema2parameters(schema, location="query")
TypeError: schema2parameters() got an unexpected keyword argument 'location' - - -`

Is there a specific version that `apispec` (or any any of the other libraries) needs to be on? I have tried several versions (including 3.00 and 4.3.0), but still get the same error.

Any help is much appreciated.

**Comment by rba-odoo** [comment]
+1 stuck here, any solution ?
