### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by chenrongxu** [OCA/rest-framework#186]
Traceback (most recent call last):
  File "/opt/odoo14/odoo-custom-addons/base_rest/http.py", line 182, in _handle_exception
    return super(HttpRestRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/odoo/http.py", line 744, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
RecursionError: maximum recursion depth exceeded

**Comment by rvalyi** [comment]
Hello @chenrongxu did you try with the recent code? because there were a similar error:
https://github.com/OCA/rest-framework/issues/116 and it was fixed in all the series, including 14.0: 
https://github.com/OCA/rest-framework/pull/122

Could you test with recent code and close se issue if it's fixed for you?
