### ISSUE TITLE
New API system not creating definitions

### ISSUE THREAD

**Issue by BartvandenHout** [OCA/rest-framework#306]
## Module
base_rest / base_rest_demo

## Describe the bug
New API system not creating definitions, ie. /api-docs/base_rest_demo_api/new_api/partner.json

## To Reproduce
**Affected versions**:
14.0

1. install base_rest_demo
2. go to /api-docs
3. select definition: base_rest_demo_api/new_api: partner

**Expected behavior**
Like the other definitions, just working ;-)

**Additional context**

Swagger Validator:
{"schemaValidationMessages":[{"level":"error","message":"Can't read from file https://[removed]/api-docs/base_rest_demo_api/new_api/partner.json"}]}

Odoo log:
2022-10-24 11:46:06,214 1045895 INFO odoodev14 werkzeug: [removed] - - [24/Oct/2022 11:46:06] "GET /api-docs/base_rest_demo_api/new_api/partner.json HTTP/1.1" 500 - 5 0.002 0.013
2022-10-24 11:46:06,221 1045895 ERROR odoodev14 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 806, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_rest/controllers/api_docs.py", line 45, in api
    openapi_doc = service.to_openapi(
  File "/usr/lib/python3/dist-packages/odoo/addons/base_rest/components/service.py", line 187, in to_openapi
    api_spec.generate_paths()
  File "/usr/lib/python3/dist-packages/odoo/addons/base_rest/apispec/base_rest_service_apispec.py", line 79, in generate_paths
    self._add_method_path(method)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_rest/apispec/base_rest_service_apispec.py", line 68, in _add_method_path
    self.path(
  File "/usr/local/lib/python3.9/dist-packages/apispec/core.py", line 526, in path
    plugin.operation_helper(path=path, operations=operations, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_rest/apispec/rest_method_param_plugin.py", line 38, in operation_helper
    responses = self._generate_responses(routing, method, params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_rest/apispec/rest_method_param_plugin.py", line 74, in _generate_responses
    output_param.to_openapi_responses(self._service, self.spec)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_rest_datamodel/restapi.py", line 77, in to_openapi_responses
    "schema": self.to_json_schema(service, spec, "output")
  File "/usr/lib/python3/dist-packages/odoo/addons/base_rest_datamodel/restapi.py", line 86, in to_json_schema
    return converter.resolve_nested_schema(schema)
  File "/usr/local/lib/python3.9/dist-packages/apispec/ext/marshmallow/openapi.py", line 117, in resolve_nested_schema
    json_schema = self.schema2jsonschema(schema_instance)
  File "/usr/local/lib/python3.9/dist-packages/apispec/ext/marshmallow/openapi.py", line 249, in schema2jsonschema
    jsonschema = self.fields2jsonschema(fields, partial=partial)
  File "/usr/local/lib/python3.9/dist-packages/apispec/ext/marshmallow/openapi.py", line 274, in fields2jsonschema
    prop = self.field2property(field_obj)
  File "/usr/local/lib/python3.9/dist-packages/apispec/ext/marshmallow/field_converter.py", line 174, in field2property
    ret.update(attr_func(field, ret=ret))
  File "/usr/local/lib/python3.9/dist-packages/apispec/ext/marshmallow/field_converter.py", line 293, in field2nullable
    if self.openapi_version.major < 3:
Exception

**Comment by BartvandenHout** [comment]
I traced it back to apispec > 5.2.2 (current is 6.0.1). So it works up to 5.2.2.

FYI:
I stopped my trace when I came upon this change in apispec
**base_rest_datamodel /restapi.py**
**to_json_schema** did't return the requested dict.

I guess this change has something todo with it.
https://github.com/marshmallow-code/apispec/commit/e5662492b9df0c0687fdfcba09871aa3a70a8e6f

**Comment by BartvandenHout** [comment]
I traced it back to apispec > 5.1.1 (current is 6.0.1). So it works up to 5.1.1.

FYI:
I stopped my trace when I came upon this change in apispec
**base_rest_datamodel /restapi.py**
**to_json_schema** did't return the requested dict.

I guess this change has something todo with it.
https://github.com/marshmallow-code/apispec/commit/e5662492b9df0c0687fdfcba09871aa3a70a8e6f
