### ISSUE TITLE
Pydantic v2 release breaks base_rest_pydantic

### ISSUE THREAD

**Issue by oerp-odoo** [OCA/rest-framework#357]
## Module
The name of the module that has a bug.

`base_rest_pydantic`

## Describe the bug

After pydantic major version v2 was released, it now by default installs this version, which is no longer compatible with old code.

## To Reproduce
**Affected versions**:

Noticed this on Odoo v15, but most likely affects other versions as well.

1. Install dependencies from requirements.txt
2. Try to install `base_rest_pydantic`

Throws this error:

```
For further information visit https://errors.pydantic.dev/2.0/u/import-error 
2023-07-01 12:42:52,275 7 WARNING odoodb odoo.modules.loading: Transient module states were reset 
2023-07-01 12:42:52,276 7 ERROR odoodb odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 474, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 179, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/odoo/odoo/modules/module.py", line 403, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/projects/project/external/oca-rest-framework/base_rest_pydantic/__init__.py", line 1, in <module>
    from . import restapi
  File "/opt/odoo/projects/project/external/oca-rest-framework/base_rest_pydantic/restapi.py", line 9, in <module>
    from pydantic import BaseModel, ValidationError, validate_model
  File "/opt/odoo/venv/lib/python3.9/site-packages/pydantic/__init__.py", line 206, in __getattr__
    return _getattr_migration(attr_name)
  File "/opt/odoo/venv/lib/python3.9/site-packages/pydantic/_migration.py", line 285, in wrapper
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
pydantic.errors.PydanticImportError: `pydantic:validate_model` has been removed in V2.
```

**Expected behavior**
Should either pin to v1 or refactor to support v2.

**Comment by zamberjo** [comment]
For v15.0 also gives error:
```
Error processing line 1 of /usr/local/lib/python3.8/site-packages/extendable_pydantic_patcher.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.8/site-packages/extendable_pydantic/__init__.py", line 4, in <module>
      from .main import ExtendableModelMeta
    File "/usr/local/lib/python3.8/site-packages/extendable_pydantic/main.py", line 8, in <module>
      from pydantic.fields import ModelField
  ImportError: cannot import name 'ModelField' from 'pydantic.fields' (/usr/local/lib/python3.8/site-packages/pydantic/fields.py)
```

SEE: https://github.com/lmignon/extendable-pydantic/blob/f4f0d8e56665a1023b2f84929d226ef2a9808719/src/extendable_pydantic/main.py#L8

`ModelField` is available on [pydantic v1.10.11](https://github.com/pydantic/pydantic/blob/15c82d978d9e3b3893f00982b9e0c5c8d5c7821d/pydantic/fields.py#L365)

**Comment by florian-dacosta** [comment]
This also break v16 fastapi module
FYI @lmignon

**Comment by lmignon** [comment]
@florian-dacosta @zamberjo  @oerp-odoo  pydantic V2 is not yet supported. I plan to work on it for fastapi in the coming weeks. The easier solution is to add a restriction on the dependency declaration...

**Comment by oerp-odoo** [comment]
Looks like pining `pydantic`, `<v2`  is not enough, because was recently released: https://pypi.org/project/extendable-pydantic/1.0.0/ and it requires pydantic `v2`.

So I get this error:

```
 > [ 7/12] RUN pip-compile-install /opt/odoo/requirements:                                                                                                                                                 
#0 0.255 + pip-compile-install /opt/odoo/requirements                                                                                                                                                      
#0 19.64 Could not find a version that matches pydantic<2,>=2.0.2 (from -r /opt/odoo/requirements/oca-rest-framework.in (line 13))                                                                         
#0 19.64 Tried: 0.0.1, 0.0.1, 0.0.2, 0.0.2, 0.0.3, 0.0.3, 0.0.4, 0.0.4, 0.0.5, 0.0.5, 0.0.6, 0.0.6, 0.0.7, 0.0.7, 0.0.8, 0.0.8, 0.1, 0.1, 0.2, 0.2, 0.2.1, 0.2.1, 0.3, 0.3, 0.4, 0.4, 0.5, 0.5, 0.6, 0.6, 0.6.1, 0.6.1, 0.6.2, 0.6.2, 0.6.3, 0.6.3, 0.6.4, 0.6.4, 0.7, 0.7, 0.7.1, 0.7.1, 0.8, 0.8, 0.9, 0.9, 0.9.1, 0.9.1, 0.10, 0.10, 0.11, 0.11, 0.11.1, 0.11.1, 0.11.2, 0.11.2, 0.12, 0.12, 0.12.1, 0.12.1, 0.13, 0.13, 0.13.1, 0.13.1, 0.14, 0.14, 0.15, 0.15, 0.16, 0.16, 0.16.1, 0.16.1, 0.17, 0.17, 0.18, 0.18.1, 0.18.2, 0.19, 0.19, 0.20, 0.20, 0.20.1, 0.20.1, 0.21, 0.21, 0.22, 0.22, 0.23, 0.23, 0.24, 0.24, 0.25, 0.25, 0.26, 0.26, 0.27, 0.27, 0.28, 0.28, 0.29, 0.29, 0.30, 0.30, 0.30.1, 0.30.1, 0.31, 0.31, 0.31.1, 0.31.1, 0.32, 0.32, 0.32.1, 0.32.1, 0.32.2, 0.32.2, 1.0, 1.0, 1.1, 1.1, 1.1.1, 1.1.1, 1.2, 1.2, 1.3, 1.3, 1.4, 1.4, 1.5, 1.5, 1.5.1, 1.5.1, 1.6, 1.6, 1.6.1, 1.6.1, 1.6.2, 1.6.2, 1.7, 1.7, 1.7, 1.7.1, 1.7.1, 1.7.1, 1.7.2, 1.7.2, 1.7.2, 1.7.3, 1.7.3, 1.7.3, 1.7.4, 1.7.4, 1.7.4, 1.8, 1.8, 1.8, 1.8.1, 1.8.1, 1.8.1, 1.8.2, 1.8.2, 1.8.2, 1.9.0, 1.9.0, 1.9.0, 1.9.1, 1.9.1, 1.9.1, 1.9.2, 1.9.2, 1.9.2, 1.10.0, 1.10.0, 1.10.0, 1.10.1, 1.10.1, 1.10.1, 1.10.2, 1.10.2, 1.10.2, 1.10.3, 1.10.3, 1.10.3, 1.10.4, 1.10.4, 1.10.4, 1.10.5, 1.10.5, 1.10.5, 1.10.6, 1.10.6, 1.10.6, 1.10.7, 1.10.7, 1.10.7, 1.10.8, 1.10.8, 1.10.8, 1.10.9, 1.10.9, 1.10.9, 1.10.10, 1.10.10, 1.10.10, 1.10.11, 1.10.11, 1.10.11, 2.0, 2.0, 2.0.1, 2.0.1, 2.0.2, 2.0.2, 2.0.3, 2.0.3
#0 19.64 Skipped pre-versions: 0.20a1, 0.20a1, 0.27a1, 1.0b1, 1.0b1, 1.0b2, 1.0b2, 1.9.0a1, 1.9.0a1, 1.9.0a1, 1.9.0a2, 1.9.0a2, 1.9.0a2, 1.10.0a1, 1.10.0a1, 1.10.0a1, 1.10.0a2, 1.10.0a2, 1.10.0a2, 1.10.0b1, 1.10.0b1, 1.10.0b1, 2.0a1, 2.0a1, 2.0a2, 2.0a2, 2.0a3, 2.0a3, 2.0a4, 2.0a4, 2.0b1, 2.0b1, 2.0b2, 2.0b2, 2.0b3, 2.0b3
#0 19.64 There are incompatible versions in the resolved dependencies:
#0 19.64   pydantic<2 (from -r /opt/odoo/requirements/oca-rest-framework.in (line 13))
#0 19.64   pydantic>=2.0.2 (from extendable-pydantic==1.0.0->-r /opt/odoo/requirements/oca-rest-framework.in (line 6))
#0 19.76 Traceback (most recent call last):
#0 19.76   File "/usr/local/bin/pip-compile-install", line 59, in <module>
#0 19.77     subprocess.run(['pip-compile', '-o', output] + reqs_in, check=True)
#0 19.77   File "/usr/lib/python3.9/subprocess.py", line 528, in run
#0 19.77     raise CalledProcessError(retcode, process.args,
#0 19.77 subprocess.CalledProcessError: Command '['pip-compile', '-o', '/opt/odoo/requirements/requirements.txt', '/opt/odoo/requirements/oca-rest-framework.in', '/opt/odoo/requirements/oca-connector-requirements.in', '/opt/odoo/requirements/monimoto-requirements.in', '/opt/odoo/requirements/requirements.in', '/opt/odoo/requirements/odoo-requirements.in']' returned non-zero exit status 2.
```

So probably need to pin this as well `extendable-pydantic<1`.

**Comment by andres-pcg** [comment]
I'm having this issue as well @oerp-odoo ; where you able to resolve it?

**Comment by oerp-odoo** [comment]
> I'm having this issue as well @oerp-odoo ; where you able to resolve it?

Yeah, I pinned it to not install higher than v1

**Comment by lmignon** [comment]
@andrp92 You're welcome to fix this issue.

**Comment by andres-pcg** [comment]
I'll be more than happy. I'm going to be sending a PR later on today. 

Regards,
