### ISSUE TITLE
Couldn't load module fastapi: incompatibility with last version of extendable.pydantic

### ISSUE THREAD

**Issue by mariancuadranetkia** [OCA/rest-framework#450]
After rebuild a container, or reset runboat we have detected FastApi can be loades. We get next error:
```
2024-09-12 05:46:25,310 117 CRITICAL bfbd0c7cf-8d79-49e3-a025-8d5998735f97 odoo.modules.module: Couldn't load module fastapi 
2024-09-12 05:46:25,310 117 CRITICAL bfbd0c7cf-8d79-49e3-a025-8d5998735f97 odoo.modules.module: partially initialized module 'fastapi.utils' has no attribute 'create_response_field' (most likely due to a circular import) 
2024-09-12 05:46:25,311 117 WARNING bfbd0c7cf-8d79-49e3-a025-8d5998735f97 odoo.modules.loading: Transient module states were reset 
2024-09-12 05:46:25,311 117 ERROR bfbd0c7cf-8d79-49e3-a025-8d5998735f97 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/odoo/modules/registry.py", line 91, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/odoo/modules/loading.py", line 188, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/odoo/modules/module.py", line 471, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/mnt/data/odoo-addons-dir/fastapi/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/data/odoo-addons-dir/fastapi/models/__init__.py", line 1, in <module>
    from .fastapi_endpoint import FastapiEndpoint
  File "/mnt/data/odoo-addons-dir/fastapi/models/fastapi_endpoint.py", line 15, in <module>
    from fastapi import APIRouter, Depends, FastAPI
  File "/opt/odoo-venv/lib/python3.10/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/opt/odoo-venv/lib/python3.10/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/opt/odoo-venv/lib/python3.10/site-packages/fastapi/routing.py", line 35, in <module>
    from fastapi.dependencies.utils import (
  File "/opt/odoo-venv/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 59, in <module>
    from fastapi.utils import create_model_field, get_path_param_names
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/opt/odoo-venv/lib/python3.10/site-packages/wrapt/importer.py", line 185, in _self_exec_module
    notify_module_loaded(module)
  File "/opt/odoo-venv/lib/python3.10/site-packages/wrapt/importer.py", line 118, in notify_module_loaded
    hook(module)
  File "/opt/odoo-venv/lib/python3.10/site-packages/extendable_pydantic/_patch.py", line 70, in hook_fastapi_utils
    wrapt.wrap_function_wrapper(
  File "/opt/odoo-venv/lib/python3.10/site-packages/wrapt/patches.py", line 114, in wrap_function_wrapper
    return wrap_object(module, name, FunctionWrapper, (wrapper,))
  File "/opt/odoo-venv/lib/python3.10/site-packages/wrapt/patches.py", line 60, in wrap_object
    (parent, attribute, original) = resolve_path(module, name)
  File "/opt/odoo-venv/lib/python3.10/site-packages/wrapt/patches.py", line 48, in resolve_path
    original = lookup_attribute(parent, attribute)
  File "/opt/odoo-venv/lib/python3.10/site-packages/wrapt/patches.py", line 46, in lookup_attribute
    return getattr(parent, attribute)
AttributeError: partially initialized module 'fastapi.utils' has no attribute 'create_response_field' (most likely due to a circular import). Did you mean: 'create_cloned_field'?
```
We've tried reset runboat, and we get same error. Problem is with extendable-pydantic version, last version is 1.3.1 from 10th of September (this week). So, in our environment, we've working now with version 1.3.0, but I'm not sure if with upgrade requirements file is 'enough' or is better other strategy.

Now, we can see full log with next runboat log:
https://runboat.odoo-community.org/api/v1/builds/bfbd0c7cf-8d79-49e3-a025-8d5998735f97/init-log

I await your comments about how is the best way to proceed with this type of problems..

Thanks!

**Comment by mariancuadranetkia** [comment]
I close the issue, now its working!
